<div class="image_home"></div>
<div class="logo_home"></div>
<div class="login_section">
	<div class="login_button_facebook">
		<a href="<?php echo $this->getUrl( array('controller'=>'auth', 'action'=>'login') ); ?>">Sign in with Facebook</a>
	</div>
	<div class="login_button_apps">
		<a href="<?php echo $this->getUrl( array('controller'=>'auth', 'action'=>'login') ); ?>">Sign in with AppsAway</a>
	</div>
</div>

<div class="download_links">
	<img src="<?php echo $this->getUrl('css/img/badge_android.png'); ?>">
	<img src="<?php echo $this->getUrl('css/img/badge_ios.png'); ?>">
</div>

<div class="app_description_get">
	<table CELLSPACING=10>
		<tr>
			<td>
				<h3>GET YOUR FRIEND’S APPS</h3><br /><br />
				<p>Stop searching for apps everywhere. Appsaway shows you the apps that your friends have downloaded and shared. If one of your friends has it, you might want to have it too. </p>
			</td>
			<td>
				<img src="<?php echo $this->getUrl('css/img/image_home2.png'); ?>">
			</td>
		</tr>
	</table>
</div>

<div class="app_description_share">
	<table CELLSPACING=10>
		<tr>
			<td>
				<img src="<?php echo $this->getUrl('css/img/image_home3.png'); ?>">
			</td>
			<td>
				<h3>SHARE YOUR BEST APPS</h3><br /><br />
				<p>Select your best apps and share them with your friends on facebook, twitter and more. Be part of the Appsaway community, follow other users with similar interests and get the apps you really want.</p>
			</td>			
		</tr>
	</table>
</div>