<?php
	$this->addStyle("css/global.css");
	$this->addScript("https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js");
	$this->addScript("js/global.js");
	$this->addScript("http://connect.facebook.net/en_US/all.js#appId=".FB_APP_ID."&amp;xfbml=1");
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8">
		<title><?php echo isset($this->title)? $this->title:'No title'; ?></title>
		<?php echo $this->getHeaderIncludes(); ?>
		<script type="text/javascript">
			var base_url = '/<?php echo BASE_URL; ?>/';
			var fb_app_id = '<?php echo FB_APP_ID; ?>';
		</script>	
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
			</div>
			<div id="main_content">
				<div id="main_menu">
					<?php // $this->partial('main_menu'); ?>
				</div>
				<?php $this->getContent(); ?>
			</div>
			<div id="footer">
			</div>
		</div>
	</body>
</html>