<?php
	$user = $this->response["user"];
	//var_dump($this->response);
?>
<div id="left_column">
	<div class="logo_medium">
		<a href="<?php echo $this->getUrl( array('controller'=>'users', 'action'=>'index' )); ?>">
			<img src="<?php echo $this->getUrl('css/img/logo_profile.png'); ?>">
		</a>
	</div>
	<div class="profile_detail">
		<div class="profile_detail_user">
			<div style="float:left"><img src="<?php echo $user["picture"];?>" class="profile_image" /></div>
			<div style="float:left;margin-left: 10px;">
				<p><?php echo $user["first_name"].' '.$user["last_name"];?></p>
<!--				<a href="<?php echo $this->getUrl( array('controller'=>'users', 'action'=>'edit' )); ?>">Edit Profile</a><br />-->
				<?php 
					if($this->response["user"]["following"] == "own" && $this->response["user"]["following"] != "0") {?> 
						<a href="#" onclick="user_edit_action();">Edit Profile</a><br />
						<a href="<?php echo $this->getUrl( array('controller'=>'auth', 'action'=>'logout' )); ?>">Logout</a>
				<?php }
					else{
						if($user["following"]=="0"){
							echo '<a href="'.$this->getUrl( array('controller'=>'users', 'action'=>'follow', 'user'=>$user["id"], 'follow'=>'1' )).'">follow</a>';	
						}
						else{
							echo '<a href="'.$this->getUrl( array('controller'=>'users', 'action'=>'follow', 'user'=>$user["id"], 'follow'=>'0' )).'">Unfollow</a>';
						}
					}
				?>
			</div>
		</div>
		<div class="profile_sff">
			<div class="profile_box_sff">
				<a href="#">
					<p class="profile_box_sff_number"><?php echo $user["shares_counter"]; ?></p>
					Shared apps					
				</a>
			</div>
			<div class="profile_box_sff">
				<a href="javascript:void(0);" onclick="load_followers_following('Followin');">
					<p class="profile_box_sff_number"><?php echo $user["followings_counter"]; ?></p>
					following					
				</a>
			</div>
			<div class="profile_box_sff">
				<a href="javascript:void(0);" onclick="load_followers_following('followers');">
					<p class="profile_box_sff_number"><?php echo $user["followers_counter"]  ?></p>
					followers
				</a>
			</div>
		</div>
		<div class="my_profile_apps_menu">
			<table style="width: 100%;">
				<tr>
					<td><p>My apps</p></td>
					<td>         </td>
					<td><a href="javascript:void(0);" onclick="list_shared_apps(<?php echo $user["id"];?>);" class="my_profile_apps_menu_link_shr">Shared </a></td>
					<td><a href="javascript:void(0);" onclick="list_favorites_apps(<?php echo $user["id"];?>);" class="my_profile_apps_menu_link_fav">Favorites </a></td>
				</tr>
				<tr>
					<td colspan="4">
						<div id="apps_in_profile_menu">
						</div>
					</td>
				</tr>
			</table>
		</div>

	</div>
</div>

<div id="profile_data">
	<?php 
	echo $this->partial( 'time_line',array('response'=>$this->get_timeline_response) );
	?>
</div>

<script>
	$(document).ready(function() {
	  list_shared_apps(<?php echo $user["id"];?>);
	});
</script>