<?php
	//var_dump($this->response);
	if($this->response["shares"]){
		$apps = $this->response["shares"];
		foreach( $apps as $app){
			$app_data =$app["application"];
			//var_dump($app);		
?>		
				<div class="app_box">
					<a href="#">
						<div class="app_image">
							<img src="<?php echo $app_data["icon"]; ?>">
						</div>
						<div class="app_title">
							<?php echo $app_data["application_name"]; ?>
						</div>
					</a>
				</div>
<?php 	}		
	} 
	else{
		echo "Dont Shares";
	}
?>