<?php
	//var_dump($this->response);
	$apps = $this->response["favorites"];
	if($apps){?>
		<table>
		<?php
		foreach( $apps as $app){
			$app_data =$app["share"] ["application"];
			//var_dump($app["share"] ["application"]);		
?>		
				<div class="app_box">
					<!--<a href="<?php echo $this->getUrl( array('controller'=>'applications', 'action'=>'getData', 'shared_id'=> $app_data["shared_id"], 'package_name' =>$app_data["package_name"] )); ?>">--></a>
						<div class="app_image">
							<img src="<?php echo $app_data["icon"]; ?>" />
						</div>
						<div class="app_title">
							<?php echo $app_data["application_name"]; ?>
							<!--<div class="app_box_description_icons">
								<?php echo "1". 'Favs' ;?>
								<?php echo "1". 'Comments';?> 
								<?php echo "1". 'Shareds';?> 		
							</div>-->
						</div>
				</div>
<?php 	}
		?>
		</table>
		<?php
	} 
	else{
		echo "Dont favs";
	}
?>