<?php
	//var_dump($this->response);
	$apps = $this->response["favorites"];
	if($apps){?>
		<table>
		<?php
		foreach( $apps as $app){
			$app_data =$app["share"] ["application"];
			//var_dump($app["share"] ["application"]);		
?>		
			<?php if($app_data["package_name"]!= ""){?>
					<a href="https://play.google.com/store/apps/details?id=<?php echo $app_data["package_name"]; ?>" target="_blank">
				<?php }else{?>
					<a href="https://play.google.com/store" target="_blank">
				<?php }?>
				<div class="app_box">
						<div class="app_image">
							<img src="<?php echo $app_data["icon"]; ?>" />
						</div>
						<div class="app_title">
							<?php echo $app_data["application_name"]; ?>
							<!--<div class="app_box_description_icons" >
								<?php echo "1";
								if(!$app["is_favorite"]){
									echo '<a href="javascript:void(0);" onclick="send_fav_action('.$app["id"].',1);">Favs</a>' ;
								}
								else{
									echo '<a href="javascript:void(0);" onclick="send_fav_action('.$app["id"].',0);">UnFav</a>' ;
								}?>
								<?php echo "1". 'Cmt';?> 
								<?php echo $app_data["shares_counter"].'Shr';?> 		
							</div>-->
						</div>
				</div>
			</a>
<?php 	}
		?>
		</table>
		<?php
	} 
	else{
		echo "Dont favs";
	}
?>