<?php
	//var_dump($this->response);
	$apps = $this->response["shares"];
	foreach( $apps as $app){
		$app_data =$app["application"];
		//var_dump($app_data);			
?>
	<div class="app_box">
		<div class="app_title">
			<?php echo $app_data["application_name"]; ?>
		</div>
		<div class="app_box_description">
			<img src="<?php echo $app_data["icon"]; ?>">
			<a href="<?php echo $this->getUrl( array('controller'=>'applications', 'action'=>'getData', 'shared_id'=> $app_data["shared_id"], 'package_name' =>$app_data["package_name"] )); ?>"><h2><?php echo '<b>'.$app_data["package_name"].'</b>';?></h2></a>
			<div class="app_box_description_icons">
				<?php echo "1". '<a href="'.$this->getUrl( array('controller'=>'applications', 'action'=>'favorite', 'id'=>$app_data["id"], 'favorite'=>'1' )).'">Favs</a>' ;?>
				<?php echo "1". '<a href="#">Comments</a>';?> 
				<?php echo "1". '<a href="'.$this->getUrl( array('controller'=>'applications', 'action'=>'share', 'id'=>$app_data["id"], 'share'=>'1' )).'">Shareds</a>'  ;?> 		
			</div>
			<div class="app_description"><?php echo $app_data["description"];?></div>
			<a href="#" onclick="show_more_description();" class="readmore">Read more </a>
		</div>	
	</div>
<?php }?>