<?php
	var_dump($this->response);
	/*$apps = $this->response["applications"];
	foreach( $apps as $app){			
		$bridge = new ApplicationsBridge();
		$application = $bridge->getData($app["package_name"], $app["shared_id"] );
		$app_data = $application["app_data"];
?>
	<div class="app_box">
		<div class="app_title">
			<?php echo $app["application_name"]; ?>
		</div>
		<div class="app_box_description">
			<img src="<?php echo $app["icon"]; ?>">
			<a href="<?php echo $this->getUrl( array('controller'=>'applications', 'action'=>'getData', 'shared_id'=> $app["shared_id"], 'package_name' =>$app["package_name"] )); ?>"><h2><?php echo '<b>'.$app["package_name"].'</b>';?></h2></a>
			<div class="app_box_description_icons">
				<?php echo $app_data["favorites_counter"]. 'Favs' ;?>
				<?php echo $app_data["comments_counter"]. 'Comments'  ;?> 
				<?php echo $app_data["shares_counter"]. 'Shareds'  ;?> 		
			</div>
			<div class="app_description"><?php echo $app_data["description"];?></div>
			<a href="#" onclick="show_more_description();" class="readmore">Read more </a>
		</div>	
	</div>
<?php }*/?>