<div class="logo_login"></div>
<form action="?do=save" method="post" class="form_login">
	<table cellspacing="5">
<?php
	$this->partial( 'flash_messages', array('flash_messages'=>$this->getFlashMessages()) );
?>
		<tr>
			<td class="label" style="width:100px">
				<label for="username">Username</label>
			</td>
			<td>
				<input type="text" name="email" id="email" />
			</td>
		</tr>
		<tr>
			<td colspan="2"><br /></td>
		</tr>
		<tr>
			<td  class="label">
				<label for="password">Password</label>
			</td>
			<td>
				<input type="password" name="password" id="password" />
			</td>
		</tr>
		<tr>
			<td colspan="2"><br /></td>
		</tr>
		<tr>
			<td></td>
			<td align="center">
				<input type="submit" value="Login"  class="form_login_submit_button" />
			</td>
		</tr>
	</table>
</form>