<div class="logo_medium"></div>
<form action="?do=save" method="post" class="form_login">
	<table style="margin:50px auto;width:300px;">
<?php
	$this->partial( 'flash_messages', array('flash_messages'=>$this->getFlashMessages()) );
?>
		<tr>
			<td style="padding:2px;">
				<label for="username">Username</label>
			</td>
			<td style="padding:2px;">
				<input type="text" name="email" id="email" />
			</td>
		</tr>
		<tr>
			<td style="padding:2px;">
				<label for="password">Password</label>
			</td>
			<td style="padding:2px;">
				<input type="password" name="password" id="password" />
			</td>
		</tr>
		<tr>
			<td align="center" style="padding:5px;">
				<input type="submit" value="Login"  style="padding:2px 5px;" />
			</td>
		</tr>
	</table>
</form>