<script type="text/javascript">
$(function(){
	$('#time_line_profile').scrollPagination({
		'contentPage': '<?php echo $this->getUrl( array("controller"=>"users", "action"=>"get_time_line","more_feeds"=>"true" )); ?>', // the url you are fetching the results
		'contentData': {}, // these are the variables you can pass to the request, for example: children().size() to know which page you are
		'scrollTarget': $(window), // who gonna scroll? in this example, the full window
		'heightOffset': 10, // it gonna request when scroll is 10 pixels before the page ends
		'beforeLoad': function(){ // before load function, you can display a preloader diva
			$('#loading').fadeIn();	
		},
		'afterLoad': function(elementsLoaded){ // after loading content, you can use this function to animate your new elements
			 $('#loading').fadeOut();
			 var i = 0;
			 $(elementsLoaded).fadeInWithDelay();
			 if ($('#time_line_profile').children().size() > 100){ // if more than 100 results already loaded, then stop pagination (only for testing)
			 	$('#nomoreresults').fadeIn();
				$('#content').stopScrollPagination();
			 }
		}
	});
	
	// code for fade in element by element
	$.fn.fadeInWithDelay = function(){
		var delay = 0;
		return this.each(function(){
			$(this).delay(delay).animate({opacity:1}, 200);
			delay += 100;
		});
	};
		   
});
</script>
<div class="time_line_profile"  id="time_line_profile">
	
</div>
<div class="loading" id="loading" style="display:none">Wait a moment... it's loading!</div>
<div class="loading" id="nomoreresults" style="display:none">Sorry, no more results for your pagination demo.</div>