<div class="time_line_profile">
	<?php
	foreach( $this->response["feeds"] as $i => $feed){
	 	//var_dump($feed["share"]["application"]);
		?>
		
		<?php if($feed["type"]["id"]=="1"){ 
			$feed_text = str_replace('%user%', $feed["user"]["first_name"].' '.$feed["user"]["last_name"], $feed["text"]);
			$feed_text = str_replace('%mentioned%', $feed["mentioned_user"]["first_name"].' '.$feed["mentioned_user"]["last_name"], $feed_text);
			?>
			<div class="notification_box_tl">
				<img src="<? echo $feed["thumb"] ;?>" width="60px">
				<div class="notification_box_tl_text" id="notification_box_tl_text_<? echo $i;?>">
					<?php if($feed["type"]["id"]!="1"){ ?>
						<p>
					<? } 
					echo $feed_text; 
					?></p>
					<p class="time_indicator">1 hour ago</p>
				</div>
			</div>
		<?}else{ 
			$feed_text = str_replace('%user%', $feed["user"]["first_name"].' '.$feed["user"]["last_name"], $feed["text"]);
			$feed_text = str_replace('%application%', $feed["share"]["application"]["application_name"], $feed_text);
			?>
			<div class="notification_box_tl">
				<img src="<? echo $feed["thumb"] ;?>" width="60px">
				<div class="notification_box_tl_text" id="notification_box_tl_text_<? echo $i;?>">
					<?php if($feed["type"]["id"]!="1"){ ?>
						<a href="javascript:void(0);" onclick="openFeddDetail(<? echo $i;?>);">
					<? } 
					echo $feed_text; 
					?></a>
					<p class="time_indicator">1 hour ago</p>
				</div>
			</div>
			<div class="notification_box_detail_tl" id="notification_box_detail_tl<? echo $i;?>">
				<img src="<? echo $feed["thumb"] ;?>" width="60px">
				<div class="notification_box_tl_detail_text" >
					<? echo '<a href="https://play.google.com/store/apps/details?id='.$feed["share"]["application"]["package_name"].'" target="_blank">'.$feed["share"]["application"]["application_name"].'</a><br />'; ?>
					<? echo '<p style="color:#fff;">'.$feed["share"]["application"]["category"]["description"].'</p><br />'; ?>
					<? if($feed["share"]["is_favorite"]){
						$fav_display = "none";
						$unfav_display = "";
					   }else{
					   	$fav_display = "";
						$unfav_display = "none";
					   }
					   echo '<a href="javascript:void(0);" id="fav_icon_'.$i.'" onclick="send_fav_action('.$feed["share"]["id"].',1,'.$i.')"  style="display:'.$fav_display.'">
					  		<span class="counter_'.$i.'">'.$feed["share"]["favorites_counter"].'</span>
					   		<img src="'.$this->getUrl('css/img/fav_icon_12_10.png').'" style="float: none;"></a>' ;
					   echo '<a href="javascript:void(0);" id="unfav_icon_'.$i.'" onclick="send_fav_action('.$feed["share"]["id"].',0,'.$i.')" style="display:'.$unfav_display.'">
							<span class="counter_'.$i.'">'.$feed["share"]["favorites_counter"].'</span>
							<img src="'.$this->getUrl('css/img/un_fav_icon_12_10.png').'" style="float: none;"></a>' ;
					   echo '<p>  | '.$feed["share"]["application"]["shares_counter"].'<img src="'.$this->getUrl("css/img/share_icon_13_10.png").'" style="float: none;"></p>'; 
					   echo '<p>  | '.$feed["share"]["comments_counter"].'Comment</p>'; ?>
				</div>
				<a href="https://play.google.com/store/apps/details?id=<?php echo $feed["share"]["application"]["package_name"];?>" target="_blank">
				<div class="notification_box_tl_detail_price" >
					<?php $price = $feed["share"]["application"]["price"];
						if($price){
							echo '<p>'.$price.'</p>';
						}
						else{
							echo '<p>FREE</p>';
						}
					?>					
					<img src="<?php echo $this->getUrl('css/img/download_icon.png') ?>" />
				</div>
			</div>
			</a>
		
		<?} ?>
	<?}?>
</div>